version: '3.8'

services:
  backend-green:
    build:
      context: ./backend
      dockerfile: Dockerfile.green-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env

  frontend-green:
    build:
      context: ./frontend
      dockerfile: Dockerfile.green-frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend-green
