FROM node:18-alpine
RUN apk add --no-cache python3 make g++
WORKDIR /app
COPY package*.json ./
RUN chmod -R 777 /app
RUN npm install --force
COPY . .
RUN npm rebuild bcrypt --build-from-source
EXPOSE 8001
CMD ["npm", "start"]
