apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-blue
  namespace: webapps
  labels:
    app: app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
      version: blue
  template:
    metadata:
      labels:
        app: app
        version: blue
    spec:
      containers:
      - name: frontend
        image: beingreprobate/blue-frontend:latest
        ports:
        - containerPort: 3000
      - name: backend
        #        image: dhruv2412/blue-backend:v1.0.3
        image: beingreprobate/blue-backend:latest
        ports:
        - containerPort: 8001

