apiVersion: v1
kind: Service
metadata:
  name: green-service
  namespace: webapps
spec:
  type: ClusterIP
  selector:
    version: green  # ✅ Targets Green Deployment
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3001
      name: frontend-port
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: backend-port
