# apiVersion: v1
# kind: Service
# metadata:
#   name: app-service
# spec:
#   type: ClusterIP
#   selector:
#     app: active
#   ports:
#     - protocol: TCP
#       port: 80         
#       targetPort: 3000 
#       name: frontend-port   # ✅ Required name for frontend port
#     - protocol: TCP
#       port: 8001       
#       targetPort: 8001  
#       name: backend-port    # ✅ Required name for backend port

# apiVersion: v1
# kind: Service
# metadata:
#   name: app-service
# spec:
#   type: ClusterIP
#   selector:
#     version: active   # ✅ Correct selector for active version
#   ports:
#     - protocol: TCP
#       port: 80         
#       targetPort: 3000 
#       name: frontend-port  
#     - protocol: TCP
#       port: 8001       
#       targetPort: 8001  
#       name: backend-port
